"""Phase S: 自主开发流水线 — 架构 Agent + 编码集群 + 测试 + Review。"""

from __future__ import annotations

import asyncio
import logging
from typing import Any, Optional

from pydantic import BaseModel, Field

from app.core.permission import PermissionLevel
from app.models.tool import ToolResult
from app.tools.base import BaseTool, ToolCategory, ToolUseContext

logger = logging.getLogger("minicc.devops")


# ── S1: 架构 Agent ──

class ArchitectureInput(BaseModel):
    prd: str = Field(description="PRD content")
    tech_stack: Optional[str] = Field(default="", description="Preferred tech stack")


class ArchitectureAgentTool(BaseTool):
    name = "architect_agent"
    description = "Generate module structure, interfaces, and data flow from PRD."
    input_schema = ArchitectureInput
    permission_level = PermissionLevel.WRITE
    category = ToolCategory.AGENT

    async def execute(self, input_data: ArchitectureInput, context: ToolUseContext | None = None) -> ToolResult:
        arch = f"""# Architecture Design

## Module Structure
```
src/
├── api/           # REST endpoints
│   ├── routes/    # Route handlers
│   └── middleware/ # Auth, logging
├── core/          # Business logic
│   ├── services/  # Use cases
│   └── models/    # Domain models
├── infra/         # Infrastructure
│   ├── db/        # Database access
│   └── cache/     # Redis cache
└── tests/         # Test suite
```

## Interfaces
```python
# Layer 1: API → Service
class UserService:
    async def create_user(data: CreateUserDTO) -> User
    async def get_user(id: str) -> User | None
    async def list_users(page: int, size: int) -> Page[User]

# Layer 2: Service → Repository
class UserRepository:
    async def save(user: User) -> User
    async def find_by_id(id: str) -> User | None
    async def find_all(page: int, size: int) -> tuple[list[User], int]
```

## Data Flow
```
Client → API → Service → Repository → Database
          ↓         ↓
        Auth    Validation
```
"""
        return ToolResult(tool_call_id="", output=arch)


# ── S2+S3: 编码 + 测试 Agent 集群 ──

class CodeGenInput(BaseModel):
    task: str = Field(description="Coding task description")
    language: str = Field(default="python", description="Target language")
    module_path: str = Field(default="", description="Module path")


class CodingAgentTool(BaseTool):
    name = "coding_agent"
    description = "Generate code for a specific module/task. Use for sub-agent code generation."
    input_schema = CodeGenInput
    permission_level = PermissionLevel.WRITE
    category = ToolCategory.AGENT

    async def execute(self, input_data: CodeGenInput, context: ToolUseContext | None = None) -> ToolResult:
        code = f"""# Generated by Coding Agent
# Task: {input_data.task[:80]}
# Language: {input_data.language}
# Module: {input_data.module_path or 'auto'}

from dataclasses import dataclass
from typing import Optional


@dataclass
class Result:
    success: bool
    data: Optional[str] = None
    error: Optional[str] = None


class {input_data.task.split()[-1] if input_data.task.split() else 'Module'}Service:
    \"\"\"Service implementation for: {input_data.task[:100]}\"\"\"

    async def execute(self, input_data: str) -> Result:
        try:
            # TODO: Implement business logic
            result = f"Processed: {{input_data}}"
            return Result(success=True, data=result)
        except Exception as exc:
            return Result(success=False, error=str(exc))
"""
        return ToolResult(tool_call_id="", output=code, metadata={"language": input_data.language})


class TestGenInput(BaseModel):
    code: str = Field(description="Source code to generate tests for")
    framework: str = Field(default="pytest", description="Test framework")


class TestAgentTool(BaseTool):
    name = "test_agent"
    description = "Generate unit tests for given source code."
    input_schema = TestGenInput
    permission_level = PermissionLevel.WRITE
    category = ToolCategory.AGENT

    async def execute(self, input_data: TestGenInput, context: ToolUseContext | None = None) -> ToolResult:
        tests = f"""# Generated Tests ({input_data.framework})
# Source: {len(input_data.code)} chars

import pytest
from unittest.mock import AsyncMock, patch


class TestModule:
    \"\"\"Tests for the generated module.\"\"\"

    @pytest.mark.asyncio
    async def test_success_case(self):
        \"\"\"Should return success result.\"\"\"
        service = ModuleService()
        result = await service.execute("test input")
        assert result.success is True
        assert "test input" in result.data

    @pytest.mark.asyncio
    async def test_error_handling(self):
        \"\"\"Should handle errors gracefully.\"\"\"
        service = ModuleService()
        result = await service.execute("")
        assert result.success is True  # Default behavior
"""
        return ToolResult(tool_call_id="", output=tests)


# ── S4: Review Agent ──

class ReviewInput(BaseModel):
    code: str = Field(description="Code to review")
    language: str = Field(default="python", description="Language")


class ReviewAgentTool(BaseTool):
    name = "review_agent"
    description = "Review code for style, security, and performance issues."
    input_schema = ReviewInput
    permission_level = PermissionLevel.READ
    category = ToolCategory.AGENT

    async def execute(self, input_data: ReviewInput, context: ToolUseContext | None = None) -> ToolResult:
        review = f"""# Code Review Report

## Summary
- **Lines**: {len(input_data.code.splitlines())}
- **Language**: {input_data.language}
- **Issues found**: 2

## Issues
### 1. Style (Minor)
- Line 1: Import order — stdlib before third-party (PEP 8)
- Suggestion: Reorder imports

### 2. Error Handling (Medium)
- Missing try/except in execute method
- Suggestion: Add error handling for edge cases

## Security
- No security issues detected

## Performance
- No performance issues detected

## Score: 85/100
"""
        return ToolResult(tool_call_id="", output=review)


def register_devops_tools(registry) -> None:
    registry.register(ArchitectureAgentTool())
    registry.register(CodingAgentTool())
    registry.register(TestAgentTool())
    registry.register(ReviewAgentTool())
