apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-engine
  labels:
    app: python-engine
    release: prometheus
spec:
  selector:
    matchLabels:
      app: python-engine
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
