# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.grpc import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x06minicc\x1a\x0c\x63ommon.proto\"\x81\x02\n\nRunRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x15\n\rsystem_prompt\x18\x05 \x01(\t\x12 \n\x07history\x18\x06 \x03(\x0b\x32\x0f.minicc.Message\x12\x1e\n\x05tools\x18\x07 \x03(\x0b\x32\x0f.minicc.ToolDef\x12%\n\nllm_config\x18\x08 \x01(\x0b\x32\x11.minicc.LLMConfig\x12\x11\n\tmax_turns\x18\t \x01(\x05\x12\x17\n\x0ftimeout_seconds\x18\n \x01(\x03\"\x9b\x01\n\x0bRunResponse\x12\x14\n\ntext_chunk\x18\x01 \x01(\tH\x00\x12,\n\ttool_call\x18\x02 \x01(\x0b\x32\x17.minicc.ToolCallRequestH\x00\x12\x1e\n\x05usage\x18\x03 \x01(\x0b\x32\r.minicc.UsageH\x00\x12\x0f\n\x05\x65rror\x18\x04 \x01(\tH\x00\x12\x0e\n\x04\x64one\x18\x05 \x01(\x08H\x00\x42\x07\n\x05\x65vent\">\n\x0fToolCallRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\targuments\x18\x03 \x01(\t\"\xdb\x01\n\x11ToolOutputRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x14\n\x0ctool_call_id\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\x10\n\x08is_error\x18\x04 \x01(\x08\x12 \n\x07history\x18\x05 \x03(\x0b\x32\x0f.minicc.Message\x12\x1e\n\x05tools\x18\x06 \x03(\x0b\x32\x0f.minicc.ToolDef\x12%\n\nllm_config\x18\x07 \x01(\x0b\x32\x11.minicc.LLMConfig\x12\x11\n\tmax_turns\x18\x08 \x01(\x05\x32\xcd\x01\n\x0b\x41gentEngine\x12\x30\n\x03Run\x12\x12.minicc.RunRequest\x1a\x13.minicc.RunResponse0\x01\x12\x44\n\x10SubmitToolOutput\x12\x19.minicc.ToolOutputRequest\x1a\x13.minicc.RunResponse0\x01\x12\x46\n\x0bHealthCheck\x12\x1a.minicc.HealthCheckRequest\x1a\x1b.minicc.HealthCheckResponseB\"Z github.com/athenavi/minicc/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/athenavi/minicc/proto'
  _globals['_RUNREQUEST']._serialized_start=38
  _globals['_RUNREQUEST']._serialized_end=295
  _globals['_RUNRESPONSE']._serialized_start=298
  _globals['_RUNRESPONSE']._serialized_end=453
  _globals['_TOOLCALLREQUEST']._serialized_start=455
  _globals['_TOOLCALLREQUEST']._serialized_end=517
  _globals['_TOOLOUTPUTREQUEST']._serialized_start=520
  _globals['_TOOLOUTPUTREQUEST']._serialized_end=739
  _globals['_AGENTENGINE']._serialized_start=742
  _globals['_AGENTENGINE']._serialized_end=947
# @@protoc_insertion_point(module_scope)
