# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06minicc\"d\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x14\n\x0ctool_call_id\x18\x03 \x01(\t\x12$\n\ntool_calls\x18\x04 \x03(\x0b\x32\x10.minicc.ToolCall\"E\n\x07ToolDef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x17\n\x0fparameters_json\x18\x03 \x01(\t\"7\n\x08ToolCall\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\targuments\x18\x03 \x01(\t\"J\n\x05Usage\x12\x14\n\x0cinput_tokens\x18\x01 \x01(\x03\x12\x15\n\routput_tokens\x18\x02 \x01(\x03\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\x03\"U\n\tLLMConfig\x12\r\n\x05model\x18\x01 \x01(\t\x12\x12\n\nmax_tokens\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x10\n\x08provider\x18\x04 \x01(\t\"\x14\n\x12HealthCheckRequest\"F\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0e\n\x06uptime\x18\x03 \x01(\tB\"Z github.com/athenavi/minicc/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/athenavi/minicc/proto'
  _globals['_MESSAGE']._serialized_start=24
  _globals['_MESSAGE']._serialized_end=124
  _globals['_TOOLDEF']._serialized_start=126
  _globals['_TOOLDEF']._serialized_end=195
  _globals['_TOOLCALL']._serialized_start=197
  _globals['_TOOLCALL']._serialized_end=252
  _globals['_USAGE']._serialized_start=254
  _globals['_USAGE']._serialized_end=328
  _globals['_LLMCONFIG']._serialized_start=330
  _globals['_LLMCONFIG']._serialized_end=415
  _globals['_HEALTHCHECKREQUEST']._serialized_start=417
  _globals['_HEALTHCHECKREQUEST']._serialized_end=437
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=439
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=509
# @@protoc_insertion_point(module_scope)
