# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import knowledge_pb2 as knowledge__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in knowledge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeEngineStub:
    """知识库引擎服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuildDocument = channel.unary_stream(
                '/minicc.KnowledgeEngine/BuildDocument',
                request_serializer=knowledge__pb2.BuildDocumentRequest.SerializeToString,
                response_deserializer=knowledge__pb2.BuildDocumentResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/minicc.KnowledgeEngine/Query',
                request_serializer=knowledge__pb2.QueryRequest.SerializeToString,
                response_deserializer=knowledge__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/minicc.KnowledgeEngine/HealthCheck',
                request_serializer=common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class KnowledgeEngineServicer:
    """知识库引擎服务
    """

    def BuildDocument(self, request, context):
        """构建文档索引（解析 + 分块 + 嵌入）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """查询知识库（RAG 语义检索）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuildDocument': grpc.unary_stream_rpc_method_handler(
                    servicer.BuildDocument,
                    request_deserializer=knowledge__pb2.BuildDocumentRequest.FromString,
                    response_serializer=knowledge__pb2.BuildDocumentResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=knowledge__pb2.QueryRequest.FromString,
                    response_serializer=knowledge__pb2.QueryResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common__pb2.HealthCheckRequest.FromString,
                    response_serializer=common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minicc.KnowledgeEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('minicc.KnowledgeEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeEngine:
    """知识库引擎服务
    """

    @staticmethod
    def BuildDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/minicc.KnowledgeEngine/BuildDocument',
            knowledge__pb2.BuildDocumentRequest.SerializeToString,
            knowledge__pb2.BuildDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minicc.KnowledgeEngine/Query',
            knowledge__pb2.QueryRequest.SerializeToString,
            knowledge__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minicc.KnowledgeEngine/HealthCheck',
            common__pb2.HealthCheckRequest.SerializeToString,
            common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
