# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: knowledge.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'knowledge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fknowledge.proto\x12\x06minicc\x1a\x0c\x63ommon.proto\"\xbc\x01\n\x14\x42uildDocumentRequest\x12\r\n\x05kb_id\x18\x01 \x01(\t\x12\x0e\n\x06\x64oc_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x11\n\tfile_type\x18\x04 \x01(\t\x12\x10\n\x08\x66ilename\x18\x05 \x01(\t\x12\x11\n\ttenant_id\x18\x06 \x01(\t\x12\x11\n\tvector_db\x18\x07 \x01(\t\x12\x12\n\nchunk_size\x18\x08 \x01(\x05\x12\x15\n\rchunk_overlap\x18\t \x01(\x05\"\x87\x01\n\x15\x42uildDocumentResponse\x12)\n\x08progress\x18\x01 \x01(\x0b\x32\x15.minicc.BuildProgressH\x00\x12)\n\x08\x63omplete\x18\x02 \x01(\x0b\x32\x15.minicc.BuildCompleteH\x00\x12\x0f\n\x05\x65rror\x18\x03 \x01(\tH\x00\x42\x07\n\x05\x65vent\"@\n\rBuildProgress\x12\x0c\n\x04step\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x02\x12\x0f\n\x07message\x18\x03 \x01(\t\"\\\n\rBuildComplete\x12\x13\n\x0b\x63hunk_count\x18\x01 \x01(\x05\x12\x12\n\nchar_count\x18\x02 \x01(\x03\x12\x12\n\npage_count\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\t\"a\n\x0cQueryRequest\x12\r\n\x05kb_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\r\n\x05top_k\x18\x03 \x01(\x05\x12\x11\n\tthreshold\x18\x04 \x01(\x02\x12\x11\n\tvector_db\x18\x05 \x01(\t\"5\n\rQueryResponse\x12$\n\x07results\x18\x01 \x03(\x0b\x32\x13.minicc.QueryResult\"^\n\x0bQueryResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0e\n\x06\x64oc_id\x18\x03 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x04 \x01(\x05\x12\r\n\x05score\x18\x05 \x01(\x02\x32\xdf\x01\n\x0fKnowledgeEngine\x12N\n\rBuildDocument\x12\x1c.minicc.BuildDocumentRequest\x1a\x1d.minicc.BuildDocumentResponse0\x01\x12\x34\n\x05Query\x12\x14.minicc.QueryRequest\x1a\x15.minicc.QueryResponse\x12\x46\n\x0bHealthCheck\x12\x1a.minicc.HealthCheckRequest\x1a\x1b.minicc.HealthCheckResponseB\"Z github.com/athenavi/minicc/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'knowledge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/athenavi/minicc/proto'
  _globals['_BUILDDOCUMENTREQUEST']._serialized_start=42
  _globals['_BUILDDOCUMENTREQUEST']._serialized_end=230
  _globals['_BUILDDOCUMENTRESPONSE']._serialized_start=233
  _globals['_BUILDDOCUMENTRESPONSE']._serialized_end=368
  _globals['_BUILDPROGRESS']._serialized_start=370
  _globals['_BUILDPROGRESS']._serialized_end=434
  _globals['_BUILDCOMPLETE']._serialized_start=436
  _globals['_BUILDCOMPLETE']._serialized_end=528
  _globals['_QUERYREQUEST']._serialized_start=530
  _globals['_QUERYREQUEST']._serialized_end=627
  _globals['_QUERYRESPONSE']._serialized_start=629
  _globals['_QUERYRESPONSE']._serialized_end=682
  _globals['_QUERYRESULT']._serialized_start=684
  _globals['_QUERYRESULT']._serialized_end=778
  _globals['_KNOWLEDGEENGINE']._serialized_start=781
  _globals['_KNOWLEDGEENGINE']._serialized_end=1004
# @@protoc_insertion_point(module_scope)
