# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import common_pb2 as common__pb2
from app.grpc import memory_pb2 as memory__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryEngineStub:
    """记忆管理引擎服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveMemory = channel.unary_unary(
                '/minicc.MemoryEngine/SaveMemory',
                request_serializer=memory__pb2.SaveMemoryRequest.SerializeToString,
                response_deserializer=memory__pb2.SaveMemoryResponse.FromString,
                _registered_method=True)
        self.QueryMemory = channel.unary_unary(
                '/minicc.MemoryEngine/QueryMemory',
                request_serializer=memory__pb2.QueryMemoryRequest.SerializeToString,
                response_deserializer=memory__pb2.QueryMemoryResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/minicc.MemoryEngine/HealthCheck',
                request_serializer=common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class MemoryEngineServicer:
    """记忆管理引擎服务
    """

    def SaveMemory(self, request, context):
        """保存记忆
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMemory(self, request, context):
        """查询记忆
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMemory,
                    request_deserializer=memory__pb2.SaveMemoryRequest.FromString,
                    response_serializer=memory__pb2.SaveMemoryResponse.SerializeToString,
            ),
            'QueryMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMemory,
                    request_deserializer=memory__pb2.QueryMemoryRequest.FromString,
                    response_serializer=memory__pb2.QueryMemoryResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common__pb2.HealthCheckRequest.FromString,
                    response_serializer=common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minicc.MemoryEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('minicc.MemoryEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryEngine:
    """记忆管理引擎服务
    """

    @staticmethod
    def SaveMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minicc.MemoryEngine/SaveMemory',
            memory__pb2.SaveMemoryRequest.SerializeToString,
            memory__pb2.SaveMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minicc.MemoryEngine/QueryMemory',
            memory__pb2.QueryMemoryRequest.SerializeToString,
            memory__pb2.QueryMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minicc.MemoryEngine/HealthCheck',
            common__pb2.HealthCheckRequest.SerializeToString,
            common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
