# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memory.proto
# Protobuf Python Version: 6.33.5
"""."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.grpc import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmemory.proto\x12\x06minicc\x1a\x0c\x63ommon.proto\"\xdd\x01\n\x11SaveMemoryRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x13\n\x0bmemory_type\x18\x05 \x01(\t\x12\x39\n\x08metadata\x18\x06 \x03(\x0b\x32\'.minicc.SaveMemoryRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"F\n\x12SaveMemoryResponse\x12\x11\n\tmemory_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"k\n\x12QueryMemoryRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\x12\r\n\x05top_k\x18\x04 \x01(\x05\x12\x13\n\x0bmemory_type\x18\x05 \x01(\t\"<\n\x13QueryMemoryResponse\x12%\n\x07results\x18\x01 \x03(\x0b\x32\x14.minicc.MemoryResult\"\xd5\x01\n\x0cMemoryResult\x12\x11\n\tmemory_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\trelevance\x18\x03 \x01(\x02\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x13\n\x0bmemory_type\x18\x05 \x01(\t\x12\x34\n\x08metadata\x18\x06 \x03(\x0b\x32\".minicc.MemoryResult.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xe3\x01\n\x0cMemoryEngine\x12\x43\n\nSaveMemory\x12\x19.minicc.SaveMemoryRequest\x1a\x1a.minicc.SaveMemoryResponse\x12\x46\n\x0bQueryMemory\x12\x1a.minicc.QueryMemoryRequest\x1a\x1b.minicc.QueryMemoryResponse\x12\x46\n\x0bHealthCheck\x12\x1a.minicc.HealthCheckRequest\x1a\x1b.minicc.HealthCheckResponseB\"Z github.com/athenavi/minicc/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/athenavi/minicc/proto'
  _globals['_SAVEMEMORYREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_SAVEMEMORYREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_MEMORYRESULT_METADATAENTRY']._loaded_options = None
  _globals['_MEMORYRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SAVEMEMORYREQUEST']._serialized_start=39
  _globals['_SAVEMEMORYREQUEST']._serialized_end=260
  _globals['_SAVEMEMORYREQUEST_METADATAENTRY']._serialized_start=213
  _globals['_SAVEMEMORYREQUEST_METADATAENTRY']._serialized_end=260
  _globals['_SAVEMEMORYRESPONSE']._serialized_start=262
  _globals['_SAVEMEMORYRESPONSE']._serialized_end=332
  _globals['_QUERYMEMORYREQUEST']._serialized_start=334
  _globals['_QUERYMEMORYREQUEST']._serialized_end=441
  _globals['_QUERYMEMORYRESPONSE']._serialized_start=443
  _globals['_QUERYMEMORYRESPONSE']._serialized_end=503
  _globals['_MEMORYRESULT']._serialized_start=506
  _globals['_MEMORYRESULT']._serialized_end=719
  _globals['_MEMORYRESULT_METADATAENTRY']._serialized_start=213
  _globals['_MEMORYRESULT_METADATAENTRY']._serialized_end=260
  _globals['_MEMORYENGINE']._serialized_start=722
  _globals['_MEMORYENGINE']._serialized_end=949
# @@protoc_insertion_point(module_scope)
