# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.grpc import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x06minicc\x1a\x0c\x63ommon.proto\"\xd1\x01\n\x14IndexDocumentRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\tfile_type\x18\x04 \x01(\t\x12<\n\x08metadata\x18\x05 \x03(\x0b\x32*.minicc.IndexDocumentRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"a\n\x15IndexDocumentResponse\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63hunks_count\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"U\n\x0fRetrieveRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\r\n\x05top_k\x18\x03 \x01(\x05\x12\x11\n\tthreshold\x18\x04 \x01(\x02\";\n\x10RetrieveResponse\x12\'\n\x07results\x18\x01 \x03(\x0b\x32\x16.minicc.RetrieveResult\"\xc0\x01\n\x0eRetrieveResult\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x10\n\x08\x63hunk_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x02\x12\x36\n\x08metadata\x18\x05 \x03(\x0b\x32$.minicc.RetrieveResult.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xe0\x01\n\tRAGEngine\x12L\n\rIndexDocument\x12\x1c.minicc.IndexDocumentRequest\x1a\x1d.minicc.IndexDocumentResponse\x12=\n\x08Retrieve\x12\x17.minicc.RetrieveRequest\x1a\x18.minicc.RetrieveResponse\x12\x46\n\x0bHealthCheck\x12\x1a.minicc.HealthCheckRequest\x1a\x1b.minicc.HealthCheckResponseB\"Z github.com/athenavi/minicc/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/athenavi/minicc/proto'
  _globals['_INDEXDOCUMENTREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_INDEXDOCUMENTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_RETRIEVERESULT_METADATAENTRY']._loaded_options = None
  _globals['_RETRIEVERESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_INDEXDOCUMENTREQUEST']._serialized_start=36
  _globals['_INDEXDOCUMENTREQUEST']._serialized_end=245
  _globals['_INDEXDOCUMENTREQUEST_METADATAENTRY']._serialized_start=198
  _globals['_INDEXDOCUMENTREQUEST_METADATAENTRY']._serialized_end=245
  _globals['_INDEXDOCUMENTRESPONSE']._serialized_start=247
  _globals['_INDEXDOCUMENTRESPONSE']._serialized_end=344
  _globals['_RETRIEVEREQUEST']._serialized_start=346
  _globals['_RETRIEVEREQUEST']._serialized_end=431
  _globals['_RETRIEVERESPONSE']._serialized_start=433
  _globals['_RETRIEVERESPONSE']._serialized_end=492
  _globals['_RETRIEVERESULT']._serialized_start=495
  _globals['_RETRIEVERESULT']._serialized_end=687
  _globals['_RETRIEVERESULT_METADATAENTRY']._serialized_start=198
  _globals['_RETRIEVERESULT_METADATAENTRY']._serialized_end=245
  _globals['_RAGENGINE']._serialized_start=690
  _globals['_RAGENGINE']._serialized_end=914
# @@protoc_insertion_point(module_scope)
