# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""."""
import grpc
import warnings

from app.grpc import common_pb2 as common__pb2
from app.grpc import rag_pb2 as rag__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RAGEngineStub:
    """RAG 检索引擎服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexDocument = channel.unary_unary(
                '/minicc.RAGEngine/IndexDocument',
                request_serializer=rag__pb2.IndexDocumentRequest.SerializeToString,
                response_deserializer=rag__pb2.IndexDocumentResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/minicc.RAGEngine/Retrieve',
                request_serializer=rag__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=rag__pb2.RetrieveResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/minicc.RAGEngine/HealthCheck',
                request_serializer=common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class RAGEngineServicer:
    """RAG 检索引擎服务
    """

    def IndexDocument(self, request, context):
        """文档索引：分块 + 嵌入 + 存入 Milvus
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """向量检索：查询相关文档片段
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RAGEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IndexDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexDocument,
                    request_deserializer=rag__pb2.IndexDocumentRequest.FromString,
                    response_serializer=rag__pb2.IndexDocumentResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=rag__pb2.RetrieveRequest.FromString,
                    response_serializer=rag__pb2.RetrieveResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common__pb2.HealthCheckRequest.FromString,
                    response_serializer=common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minicc.RAGEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('minicc.RAGEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RAGEngine:
    """RAG 检索引擎服务
    """

    @staticmethod
    def IndexDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minicc.RAGEngine/IndexDocument',
            rag__pb2.IndexDocumentRequest.SerializeToString,
            rag__pb2.IndexDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minicc.RAGEngine/Retrieve',
            rag__pb2.RetrieveRequest.SerializeToString,
            rag__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minicc.RAGEngine/HealthCheck',
            common__pb2.HealthCheckRequest.SerializeToString,
            common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
